proxy_client:
    symfony:
        http:
            servers: ['$http_cache.purge_servers$']

user_context:
    enabled: true
    hash_cache_ttl: 600
    # NOTE: These are also defined/used in AppCache, in Varnish VCL, and Fastly VCL
    session_name_prefix: eZSESSID
